name: S3 Upload
description: This GitHub action is used to upload files to Amazon S3
author: Giao Ho
inputs:
  aws_access_key_id:
    description: AWS access key ID.
    required: true
  aws_secret_access_key:
    description: AWS secret access key.
    required: true
  aws_region:
    description: The region to send service requests to.
    required: true
  aws_bucket:
    description: The bucket name to which the PUT action was initiated.
    required: true
  source:
    description: ''
    required: true
  target:
    description: ''
    required: true
  acl:
    description: The canned ACL to apply to the object
    required: true
  expires:
    description: The date and time at which the object is no longer cacheable.
    required: true
  throwing:
    description: ''
    required: false
outputs:
  succeeded:
    description: Number of successful files
  failed:
    description: Number of failed files
runs:
  using: node20
  main: action/index.js
branding:
  icon: upload-cloud
  color: red
